force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Days_Until_Due__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Due__c</fullName>
    <formula>Due_Date__c - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Until Due</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>0 is high priority.  Use integers</description>
    <inlineHelpText>0 is high priority.  Use integers</inlineHelpText>
    <label>Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Won&#39;t do</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Users__c.field-meta.xml
<CustomField>
    <fullName>Users__c</fullName>
    <description>hidden field for aggregating interested users</description>
    <inlineHelpText>hidden field for aggregating interested users</inlineHelpText>
    <label>Users</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ProjectsController.cls
public with sharing class ProjectsController {
    @AuraEnabled
    public static List<Project__c> getMyProjects(String status) {
        Id myID = UserInfo.getUserId();
        string fullname = '%' + userinfo.getFirstName() + ' ' + userInfo.getLastName() + '%'; 
        List<Project__c> projects = [SELECT Id, Name, Days_Until_Due__c, (SELECT Id, Subject, ActivityDate  FROM Tasks WHERE Status <> 'Completed' AND OwnerId = :myID ORDER BY ActivityDate ASC NULLS LAST, CreatedDate) FROM Project__c 
                                     WHERE ( OwnerId = :myID OR Users__c like: fullName )
                                       AND Status__c = :status
                                     ORDER BY Priority__c ASC];
        return projects;
    }
    
    @AuraEnabled
    public static ID newTask(String projectId, string subject) {
        Task task = new Task();
        task.Subject = subject;
        task.WhatId = projectId;
		insert task;
        return task.Id;
    }
    
    @AuraEnabled 
    public static ID newProject(String projectName, String status) {
        Project__c project = new Project__c();
        project.Name = projectName;
        project.Status__c = status;
        insert project;
        return project.Id;
    }
    
    @AuraEnabled
    public static void closeTask(String taskId) {
        Task task = [SELECT Status FROM Task WHERE Id = :taskId];
        task.Status = 'Completed';
        update task;
    }
    
    
    private static list<id> getExpandedProjects(String status){
        set<id> projectIds = new set<id>();
        // projects I am the ownerOf
        // project I have tasks associated with
        
        // projects I follow via Chatter
        map<id, Project__c> projects = new map<id, Project__c>(
            [SELECT Id, Name FROM Project__c 
             WHERE Status__c = :status]
        );
        map<id, EntitySubscription> followedProjects = new map<id, EntitySubscription>(
            [select ParentId from entitySubscription 
             where SubscriberId  =: Userinfo.getUserId() and ParentId in: projects.keySet()]
        );
        projectIds.addAll(new List<id>(followedProjects.keySet()));
        
        // projects I requested
        // projects I am requested PMM for
        
        return new list<id>(projectIds);
    }	
}