force-app/main/default/objects/Trial_Feedback__c/Trial_Feedback__c.object-meta.xml
<CustomObject>
    <label>Trial Feedback</label>
    <nameField>
        <displayFormat>TF-{0}</displayFormat>
        <label>TrialFeedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trial_Feedback__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trial_Feedback__c/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <label>OrgID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trial_Feedback__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Negative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trial_Feedback__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/feedbackService.cls
@RestResource(urlMapping='/feedback/*')
global with sharing class feedbackService {

	@HttpPost
	global static string createFeedback(string orgId, string userId, string rating, string comments, string email, string firstname, string lastname){
		Trial_Feedback__c tf = new Trial_Feedback__c();
		tf.Comments__c = comments;
		tf.Name__c = firstname + ' ' + lastname;
		tf.Email__c = email;
		tf.OrgID__c = orgId;
		tf.UserId__c = userId;
		tf.Rating__c = rating;
		system.debug(tf);
		try{
			insert tf;
			return 'Accepted';
		} catch (exception e){
			return e.getMessage();
		}
	}
}