force-app/main/default/objects/Co_Owner__c/Co_Owner__c.object-meta.xml
<CustomObject>
    <description>for project tracking, links other users to a proejct</description>
    <label>Co-Owner</label>
    <nameField>
        <label>Co-Owner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Co-Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Co_Owner__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Co-Owners</relationshipLabel>
    <relationshipName>Co_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Co_Owner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Co_Owners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Users__c.field-meta.xml
<CustomField>
    <fullName>Users__c</fullName>
    <description>hidden field for aggregating interested users</description>
    <inlineHelpText>hidden field for aggregating interested users</inlineHelpText>
    <label>Users</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CoOwnerLogic.cls
public class CoOwnerLogic {
    
	@InvocableMethod (label='Update CoOwners' description='loops through the coowners object and updates the list on the project' )
    public static void createCoOwnerList(list<string> projectIds){
        //get the project
        list<project__c> projectsToUpdate = [select id, users__c from project__c where id in: projectIds];
        
        //get the co-owners
        list<Co_Owner__c> coowners = [select id, Project__c, user__r.firstname, user__r.lastname from Co_Owner__c where project__c in: projectIds];
        map<id, list<string>> userListByProject = new map<id, list<string>>();
        
        for (project__c p:projectsToUpdate){
            list<string> temp = new list<string>();
      		userListByProject.put(p.Id, temp);
        }
        
        for (Co_Owner__c coo:coowners){            
            list<string>temp = userListByProject.get(coo.Project__c);                            
            temp.add(coo.user__r.firstname + ' ' + coo.user__r.lastname);
           	userListByProject.put(coo.Project__c, temp);
        }
        
        //build the names list        
        for (project__c p:projectsToUpdate){
        	list<string> userNames = userListByProject.get(p.Id);
            string convertedNames = String.join(userNames, ',');
            p.Users__c = convertedNames;
        }
        //update the project
        update projectsToUpdate;
    }
}